---
title: "MSDS_6372_Project2"
author: "Tamas Toth"
date: "`r Sys.Date()`"
output: html_document
  #html_document:
    #theme: cerulean
    #highlight: textmate
  github_document:
  toc: FALSE
  toc_depth: 3
  fig_width: 7
  fig_height: 5
  dev: "png"
  df_print: "default"
  includes: NULL
  md_extensions: NULL
  hard_line_breaks: TRUE
  pandoc_args: NULL
  html_preview: TRUE
  keep_html: TRUE
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Loading the necessary R libraries for the analysis
```{r message = FALSE}
# Load the necessary libraries
library(knitr)
library(rmarkdown)
# From class
library(GGally)
library(epitools)
library(MASS)
library(tidyverse)
library(car)
library(caret)
library(glmnet)
library(ROCR)
#Dasta set
library(aplore3)

# Other useful libraries
library(dplyr)
library(ggplot2)

#library(ggpubr)
#library(tidyr)
#library(plyr)
#library(ggthemes)
#library(e1071)
#library(class)
#library(stringr)
#library(sjPlot)
#library(data.table)
#library(reshape2)
#library(corrplot)
#library(naivebayes)
#library(egg)
#library(rworldmap)
#library(Hmisc)
#library(DataExplorer)
#library(selectiveInference)
#library(dlookr)
```
```{r message = FALSE}
# Turn off scientific notation
options(scipen = 100, digits = 4)
```

#### Read the data
```{r,fig.align='center',out.extra='angle=90', message = FALSE}
#Read the data
bonemed_df = glow_bonemed
attach(bonemed_df)
bonemed_df_sample = sample_n(bonemed_df, 5)
knitr::kable(bonemed_df_sample, "html")
```

